server:
  port: 8761
  
eureka:
  instance:
    hostname: 124.172.178.206
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/